### ISSUE TITLE
nuget package issue

### ISSUE THREAD

**Issue by ChrisTruncer** [secana/Native-FSharp-Library#1]
Hey,

This is probably a dumb question, still very much a newbie when it comes to C++. But I'm trying to import this solution into VS2019 and I'm basically being told that it can't find the nuget package (Microsoft.DotNet.ILCompiler). Is there an easy fix that I am likely missing?

Thanks for your help on this project!

**Comment by secana** [comment]
Hi @ChrisTruncer,

the ILCompiler is not on NuGet but on the Dotnet Respo. The file https://github.com/secana/Native-FSharp-Library/blob/master/src/NativeLib/nuget.config contains the source for the ILCompiler. If this file is right beside your *.fsproj, you can run a ´dotnet restore´ and the ILCompiler package will be downloaded.

Hope that helps!
